services:
  # Zookeeper pour Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - data_pipeline_network

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - ./scripts:/app/scripts
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - data_pipeline_network

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - data_pipeline_network

  # PostgreSQL (Pour Airflow)
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: airflow_db  # Base de données pour Airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow_db"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - data_pipeline_network

  # Apache Spark Master
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: custom-spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - JAVA_HOME=/opt/bitnami/java
      - SPARK_CLASSPATH=/opt/bitnami/spark/jars/*
    ports:
      - "8081:8080"  
      - "7078:7077" 
    volumes:
      - ./scripts:/app/scripts
    networks:
      - data_pipeline_network

  # Apache Spark Worker
  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: custom-spark:3.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_CLASSPATH=/opt/bitnami/spark/jars/*
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=4
      - JAVA_HOME=/opt/bitnami/java
    volumes:
      - ./scripts:/app/scripts
      - ./scripts:/app/scripts
    depends_on:
      - spark-master
    networks:
      - data_pipeline_network

  # # Cassandra
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      data_pipeline_network:
        ipv4_address: 172.18.0.5  # IP statique pour Cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_LISTEN_ADDRESS=172.18.0.5
      - CASSANDRA_SEEDS=172.18.0.5
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["bash", "-c", "exec cassandra -R -f"]

  # Airflow Initialization (Run once)
  airflow-init:
    build:
      context: . 
      dockerfile: Dockerfile.airflow
    image: airflow-custom:latest  
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/app/scripts
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"
    networks:
      - data_pipeline_network

  # Airflow Webserver
  airflow-webserver:
    image: airflow-custom:latest
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow_db
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8082:8080"  
    command: airflow webserver
    networks:
      - data_pipeline_network     

  # Airflow Scheduler
  airflow-scheduler:
    image: airflow-custom:latest
    container_name: airflow-scheduler
    depends_on:
      airflow-webserver:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    command: airflow scheduler
    networks:
      - data_pipeline_network

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - data_pipeline_network
    restart: always

networks:
  data_pipeline_network:
    name: data_pipeline_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16  # Définition du sous-réseau

volumes:
  postgres_data:
  cassandra_data: