FROM bitnami/spark:3.5.0

# Installer les dépendances système
USER root

# Installer curl et autres utilitaires
RUN apt-get update && apt-get install -y curl python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Installer le connecteur Cassandra pour Spark
RUN pip install cassandra-driver

USER 1001