FROM apache/airflow:2.7.1-python3.9

# # Permet d_installer des paquets si nécessaire
USER root

RUN apt-get update && apt-get install -y openjdk-11-jdk procps && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y netcat

# Copier les fichiers nécessaires
COPY requirements.txt /requirements.txt

USER airflow
# Installer les dépendances Python
RUN pip install --no-cache-dir -r /requirements.txt